runtime: go
api_version: go1

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
- url: /static
  static_dir: static
- url: /_ah/remote_api
  script: _go_app
  secure: always
- url: /admin/.*
  script: _go_app
  login: admin
- url: /.*
  script: _go_app
  secure: always
  login: required

automatic_scaling:
  max_idle_instances: 1
