runtime: go111

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico
- url: /static
  static_dir: static
- url: /admin/.*
  script: auto
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  max_idle_instances: 1
